//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bshkara.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bshkara.Core.Localization.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Agency_Address {
            get {
                return ResourceManager.GetString("Agency_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Agency_City {
            get {
                return ResourceManager.GetString("Agency_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Agency_Country {
            get {
                return ResourceManager.GetString("Agency_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Agency_Email {
            get {
                return ResourceManager.GetString("Agency_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Agency_Logo {
            get {
                return ResourceManager.GetString("Agency_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Agency_Mobile {
            get {
                return ResourceManager.GetString("Agency_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Agency_Phone {
            get {
                return ResourceManager.GetString("Agency_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade license number.
        /// </summary>
        public static string Agency_TradeLicenseNumber {
            get {
                return ResourceManager.GetString("Agency_TradeLicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Agency_Website {
            get {
                return ResourceManager.GetString("Agency_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AuditedDictionary_Name {
            get {
                return ResourceManager.GetString("AuditedDictionary_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show as picture.
        /// </summary>
        public static string DocumentTypeEntity_ShowAsPicture {
            get {
                return ResourceManager.GetString("DocumentTypeEntity_ShowAsPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital status.
        /// </summary>
        public static string Maid_MaritalStatus {
            get {
                return ResourceManager.GetString("Maid_MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (in years).
        /// </summary>
        public static string MaidEmploymentHistoryEntity_Duration {
            get {
                return ResourceManager.GetString("MaidEmploymentHistoryEntity_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa status.
        /// </summary>
        public static string Maids_VisaStatus {
            get {
                return ResourceManager.GetString("Maids_VisaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Package_Description {
            get {
                return ResourceManager.GetString("Package_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (in days).
        /// </summary>
        public static string Package_Duration {
            get {
                return ResourceManager.GetString("Package_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing count.
        /// </summary>
        public static string Package_ListingCount {
            get {
                return ResourceManager.GetString("Package_ListingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Package_Price {
            get {
                return ResourceManager.GetString("Package_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users count.
        /// </summary>
        public static string Package_UsersCount {
            get {
                return ResourceManager.GetString("Package_UsersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only latin chars.
        /// </summary>
        public static string Validation_LatinChars {
            get {
                return ResourceManager.GetString("Validation_LatinChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only latin chars and numbers.
        /// </summary>
        public static string Validation_LatinCharsAndNumbers {
            get {
                return ResourceManager.GetString("Validation_LatinCharsAndNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numbers and &quot;+&quot;.
        /// </summary>
        public static string Validation_PhoneNumber {
            get {
                return ResourceManager.GetString("Validation_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select phone code and enter phone number.
        /// </summary>
        public static string Validation_PhoneNumberAndCode {
            get {
                return ResourceManager.GetString("Validation_PhoneNumberAndCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only positive numbers.
        /// </summary>
        public static string Validation_PositiveNumbers {
            get {
                return ResourceManager.GetString("Validation_PositiveNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; is required..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; must be string with length between &apos;{2}&apos; and &apos;{1}&apos;..
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can have a max of {1} characters.
        /// </summary>
        public static string Validation_StringLengthLimit {
            get {
                return ResourceManager.GetString("Validation_StringLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} must be between {2} and {1}.
        /// </summary>
        public static string Validation_ValueMustBeBetween {
            get {
                return ResourceManager.GetString("Validation_ValueMustBeBetween", resourceCulture);
            }
        }
    }
}
