//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bshkara.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BshkaraRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BshkaraRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bshkara.Web.BshkaraRes", typeof(BshkaraRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agencies.
        /// </summary>
        public static string Agencies_Title {
            get {
                return ResourceManager.GetString("Agencies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create user.
        /// </summary>
        public static string Api_Auth_CantCreateUser {
            get {
                return ResourceManager.GetString("Api_Auth_CantCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmated password is empty.
        /// </summary>
        public static string Api_Auth_ConfirmatedPasswordEmpty {
            get {
                return ResourceManager.GetString("Api_Auth_ConfirmatedPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty..
        /// </summary>
        public static string Api_Auth_EmailIsEmpty {
            get {
                return ResourceManager.GetString("Api_Auth_EmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        public static string Api_Auth_EmailIsNotValid {
            get {
                return ResourceManager.GetString("Api_Auth_EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a confirmed email to sing in..
        /// </summary>
        public static string Api_Auth_EmailMustBeConfirmed {
            get {
                return ResourceManager.GetString("Api_Auth_EmailMustBeConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login.
        /// </summary>
        public static string Api_Auth_InvalidLogin {
            get {
                return ResourceManager.GetString("Api_Auth_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockedOut.
        /// </summary>
        public static string Api_Auth_Lockout {
            get {
                return ResourceManager.GetString("Api_Auth_Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty..
        /// </summary>
        public static string Api_Auth_PasswordIsEmpty {
            get {
                return ResourceManager.GetString("Api_Auth_PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmated password are not equals .
        /// </summary>
        public static string Api_Auth_PasswordNotEqualsConfirmatedPassword {
            get {
                return ResourceManager.GetString("Api_Auth_PasswordNotEqualsConfirmatedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this credentials not exists..
        /// </summary>
        public static string Api_Auth_UserNotExists {
            get {
                return ResourceManager.GetString("Api_Auth_UserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This maid is already booked by you.
        /// </summary>
        public static string Booking_AlreadyBooked {
            get {
                return ResourceManager.GetString("Booking_AlreadyBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete booking.
        /// </summary>
        public static string Booking_CantDeleteBooking {
            get {
                return ResourceManager.GetString("Booking_CantDeleteBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This booking is in processing.
        /// </summary>
        public static string Booking_IsInProcessing {
            get {
                return ResourceManager.GetString("Booking_IsInProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough data to book/unbook this maid.
        /// </summary>
        public static string Booking_NotEnoughData {
            get {
                return ResourceManager.GetString("Booking_NotEnoughData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This booking is not exists.
        /// </summary>
        public static string Booking_NotExists {
            get {
                return ResourceManager.GetString("Booking_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string Booking_Title {
            get {
                return ResourceManager.GetString("Booking_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t unbook this maid.
        /// </summary>
        public static string Booking_UnCantBookMaid {
            get {
                return ResourceManager.GetString("Booking_UnCantBookMaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete city.
        /// </summary>
        public static string Cities_CantDeleteExistsInMaid {
            get {
                return ResourceManager.GetString("Cities_CantDeleteExistsInMaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities_Title {
            get {
                return ResourceManager.GetString("Cities_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016 © Agilies software development &amp; design.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete country, becourese it exists in agencies.
        /// </summary>
        public static string Countries_CantDeleteExistsInAgencies {
            get {
                return ResourceManager.GetString("Countries_CantDeleteExistsInAgencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete country, becourese it exists in maid employment history.
        /// </summary>
        public static string Countries_CantDeleteExistsInMaidEmploymentHistory {
            get {
                return ResourceManager.GetString("Countries_CantDeleteExistsInMaidEmploymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries_Title {
            get {
                return ResourceManager.GetString("Countries_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete document type, becourese it exists in maids documents.
        /// </summary>
        public static string DocumentTypes_CantDeleteExistsInMaidDocuments {
            get {
                return ResourceManager.GetString("DocumentTypes_CantDeleteExistsInMaidDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document types.
        /// </summary>
        public static string DocumentTypes_Title {
            get {
                return ResourceManager.GetString("DocumentTypes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete country, becourese it exists in maids langueges.
        /// </summary>
        public static string Languages_CantDeleteExistsInMaidLanguages {
            get {
                return ResourceManager.GetString("Languages_CantDeleteExistsInMaidLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages_Title {
            get {
                return ResourceManager.GetString("Languages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency name.
        /// </summary>
        public static string Login_AgencyName {
            get {
                return ResourceManager.GetString("Login_AgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Login_ConfirmPassword {
            get {
                return ResourceManager.GetString("Login_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail address below to reset your password..
        /// </summary>
        public static string Login_EnterEmailToReset {
            get {
                return ResourceManager.GetString("Login_EnterEmailToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password?.
        /// </summary>
        public static string Login_ForgetPassword {
            get {
                return ResourceManager.GetString("Login_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or login with.
        /// </summary>
        public static string Login_OrLoginWith {
            get {
                return ResourceManager.GetString("Login_OrLoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string Login_Register {
            get {
                return ResourceManager.GetString("Login_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string Login_Remember {
            get {
                return ResourceManager.GetString("Login_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Login_SignIn {
            get {
                return ResourceManager.GetString("Login_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maids.
        /// </summary>
        public static string Maid_Title {
            get {
                return ResourceManager.GetString("Maid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maid documents.
        /// </summary>
        public static string MaidDocuments_Title {
            get {
                return ResourceManager.GetString("MaidDocuments_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maids employment histories.
        /// </summary>
        public static string MaidEmploymentHistories_Title {
            get {
                return ResourceManager.GetString("MaidEmploymentHistories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maid languages.
        /// </summary>
        public static string MaidLanguages_Title {
            get {
                return ResourceManager.GetString("MaidLanguages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete maid, becourese it exists in booking.
        /// </summary>
        public static string Maids_CantDeleteExistsInBooking {
            get {
                return ResourceManager.GetString("Maids_CantDeleteExistsInBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maid skills.
        /// </summary>
        public static string MaidSkills_Title {
            get {
                return ResourceManager.GetString("MaidSkills_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationalities.
        /// </summary>
        public static string Nationalities_Title {
            get {
                return ResourceManager.GetString("Nationalities_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete package, becourese it exists in agency.
        /// </summary>
        public static string Packages_CantDeleteExistsInAgencyPackage {
            get {
                return ResourceManager.GetString("Packages_CantDeleteExistsInAgencyPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Register {
            get {
                return ResourceManager.GetString("Register_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills_Title {
            get {
                return ResourceManager.GetString("Skills_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the editing of data have been changed by someone else and no longer relevant. Refresh the page and try again..
        /// </summary>
        public static string Warning_DataWasChenged {
            get {
                return ResourceManager.GetString("Warning_DataWasChenged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes. Try again, and if the problem persists, see your system administrator..
        /// </summary>
        public static string Warning_UnableToSave {
            get {
                return ResourceManager.GetString("Warning_UnableToSave", resourceCulture);
            }
        }
    }
}
